/*
 * Sovereign Risk Lab — dashboard rendering.
 *
 * This file ONLY renders data/processed/*.json produced by scripts/process.py.
 * No business logic, no computed metrics, no fabricated numbers live here —
 * per the project's architecture rule (raw -> Python -> JSON -> presentation).
 * If a fetch fails (pipeline hasn't been run yet), the dashboard shows an
 * explicit "no data" state rather than falling back to placeholder numbers.
 */

const DATA_DIR = "../data/processed/";

const COUNTRIES = {
  ZWE: { name: "Zimbabwe", color: "var(--series-zwe)", order: 0 },
  KEN: { name: "Kenya", color: "var(--series-ken)", order: 1 },
  MWI: { name: "Malawi", color: "var(--series-mwi)", order: 2 },
};
const COUNTRY_ORDER = ["ZWE", "KEN", "MWI"];

// ---------------------------------------------------------------------
// Data loading
// ---------------------------------------------------------------------

async function loadJSON(filename) {
  const resp = await fetch(DATA_DIR + filename, { cache: "no-store" });
  if (!resp.ok) {
    throw new Error(`${filename}: HTTP ${resp.status}`);
  }
  return resp.json();
}

async function loadAllData() {
  const files = [
    "meta.json",
    "panel.json",
    "latest_snapshot.json",
    "devaluation_events.json",
    "policy_rate_decisions.json",
    "imf_program_status.json",
  ];
  const results = {};
  const missing = [];
  for (const f of files) {
    try {
      results[f.replace(".json", "")] = await loadJSON(f);
    } catch (err) {
      missing.push(f);
    }
  }
  return { data: results, missing };
}

// ---------------------------------------------------------------------
// Small DOM helpers
// ---------------------------------------------------------------------

function el(tag, attrs = {}, children = []) {
  const node = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) {
    if (k === "class") node.className = v;
    else if (k === "html") node.innerHTML = v; // only used with fixed, non-data strings
    else node.setAttribute(k, v);
  }
  for (const child of [].concat(children)) {
    if (child == null) continue;
    // Anything that isn't already a DOM Node (string, number, etc.) becomes
    // a text node. This bug bit us once already with a numeric `year`
    // column value silently reaching appendChild() - see tests/ if this
    // regresses (frontend has no automated tests; caught via Playwright
    // console/pageerror checks during manual verification instead).
    node.appendChild(child instanceof Node ? child : document.createTextNode(String(child)));
  }
  return node;
}

function svgEl(tag, attrs = {}) {
  const node = document.createElementNS("http://www.w3.org/2000/svg", tag);
  for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
  return node;
}

function fmtNum(v, digits = 1) {
  if (v === null || v === undefined || Number.isNaN(v)) return "—";
  return Number(v).toLocaleString(undefined, { maximumFractionDigits: digits, minimumFractionDigits: 0 });
}

function fmtPct(v, digits = 1) {
  if (v === null || v === undefined || Number.isNaN(v)) return "—";
  return `${fmtNum(v, digits)}%`;
}

// ---------------------------------------------------------------------
// Header / banner
// ---------------------------------------------------------------------

function renderHeaderMeta(meta) {
  const container = document.getElementById("header-meta");
  container.innerHTML = "";
  const badgeRow = el("div", { class: "badge-row" });
  if (meta) {
    badgeRow.appendChild(el("span", { class: "badge badge-live" }, "Live pipeline output"));
  }
  container.appendChild(badgeRow);
  if (meta) {
    const finished = new Date(meta.run_finished_at_utc);
    container.appendChild(el("div", {}, `Last refreshed ${finished.toLocaleString()} UTC`));
  }
}

function renderDataStateBanner(missing) {
  const banner = document.getElementById("data-state-banner");
  if (missing.length === 0) {
    banner.hidden = true;
    return;
  }
  banner.hidden = false;
  banner.innerHTML = "";
  banner.appendChild(el("strong", {}, "No processed data found. "));
  banner.appendChild(document.createTextNode(
    `This dashboard reads from data/processed/, which is generated by running the Python pipeline ` +
    `(python scripts/process.py) — it is not checked into the repo, since it depends on live IMF/World ` +
    `Bank/ZimRate data at the time you run it. Missing files: ${missing.join(", ")}.`
  ));
}

// ---------------------------------------------------------------------
// Generic SVG chart engine
// ---------------------------------------------------------------------

function makeChartSVG(container, { width = 640, height = 320, margin = { top: 16, right: 20, bottom: 32, left: 48 } }) {
  container.innerHTML = "";
  const svg = svgEl("svg", { viewBox: `0 0 ${width} ${height}`, role: "img" });
  container.appendChild(svg);
  return { svg, width, height, margin };
}

function scaleLinear(domain, range) {
  const [d0, d1] = domain, [r0, r1] = range;
  const span = d1 - d0 || 1;
  return (v) => r0 + ((v - d0) / span) * (r1 - r0);
}

function scaleLog(domain, range) {
  const lo = Math.max(domain[0], 1e-6);
  const hi = Math.max(domain[1], lo * 10);
  const logLo = Math.log10(lo), logHi = Math.log10(hi);
  const [r0, r1] = range;
  const span = (logHi - logLo) || 1;
  return (v) => {
    const vv = Math.max(v, lo);
    return r0 + ((Math.log10(vv) - logLo) / span) * (r1 - r0);
  };
}

function niceLogTicks(domain) {
  const lo = Math.max(domain[0], 1e-6);
  const hi = Math.max(domain[1], lo * 10);
  const startExp = Math.floor(Math.log10(lo));
  const endExp = Math.ceil(Math.log10(hi));
  const ticks = [];
  for (let e = startExp; e <= endExp; e++) ticks.push(Math.pow(10, e));
  return ticks;
}

function niceLinearTicks(domain, count = 4) {
  const [lo, hi] = domain;
  const span = hi - lo || 1;
  const step = span / count;
  const ticks = [];
  for (let i = 0; i <= count; i++) ticks.push(lo + step * i);
  return ticks;
}

let tooltipEl = null;
function getTooltip() {
  if (!tooltipEl) {
    tooltipEl = el("div", { class: "viz-tooltip" });
    tooltipEl.style.display = "none";
    document.body.appendChild(tooltipEl);
  }
  return tooltipEl;
}

function showTooltip(x, y, titleText, rows) {
  const tip = getTooltip();
  tip.innerHTML = "";
  tip.appendChild(el("div", { class: "tt-title" }, titleText));
  for (const row of rows) {
    const keyWrap = el("span", { class: "tt-key" }, [
      el("span", { class: "tt-swatch", style: `background:${row.color}` }),
      document.createTextNode(row.label),
    ]);
    keyWrap.style.setProperty("--swatch-color", row.color);
    const swatch = keyWrap.querySelector(".tt-swatch");
    swatch.style.background = row.color;
    tip.appendChild(el("div", { class: "tt-row" }, [
      keyWrap,
      el("span", { class: "tt-value" }, row.value),
    ]));
  }
  tip.style.display = "block";
  tip.style.left = `${x + 14}px`;
  tip.style.top = `${y + 14}px`;
}

function hideTooltip() {
  if (tooltipEl) tooltipEl.style.display = "none";
}

// ---------------------------------------------------------------------
// Multi-line chart (used for inflation / reserves / debt trends)
// ---------------------------------------------------------------------

function renderLineChart(containerId, { series, yLabel, useLogScale = false, valueFormatter = (v) => fmtNum(v) }) {
  const container = document.getElementById(containerId);
  const { svg, width, height, margin } = makeChartSVG(container, {
    width: 640, height: 300, margin: { top: 16, right: 56, bottom: 32, left: 48 },
  });
  const plotW = width - margin.left - margin.right;
  const plotH = height - margin.top - margin.bottom;

  const allYears = [...new Set(series.flatMap((s) => s.points.map((p) => p.year)))].sort((a, b) => a - b);
  const allValues = series.flatMap((s) => s.points.map((p) => p.value)).filter((v) => v !== null && !Number.isNaN(v));

  if (allYears.length === 0 || allValues.length === 0) {
    container.appendChild(el("p", { class: "section-note" }, "No data available."));
    return;
  }

  const xScale = scaleLinear([allYears[0], allYears[allYears.length - 1]], [margin.left, margin.left + plotW]);
  const yDomain = useLogScale
    ? [Math.max(Math.min(...allValues), 1e-3), Math.max(...allValues)]
    : [Math.min(0, Math.min(...allValues)), Math.max(...allValues) * 1.1];
  const yScale = useLogScale ? scaleLog(yDomain, [margin.top + plotH, margin.top]) : scaleLinear(yDomain, [margin.top + plotH, margin.top]);
  const yTicks = useLogScale ? niceLogTicks(yDomain) : niceLinearTicks(yDomain);

  const plot = svgEl("g", {});
  svg.appendChild(plot);

  // Gridlines + y-axis labels
  for (const t of yTicks) {
    const y = yScale(t);
    plot.appendChild(svgEl("line", { class: "gridline", x1: margin.left, x2: margin.left + plotW, y1: y, y2: y }));
    const label = svgEl("text", { class: "axis-label", x: margin.left - 8, y: y + 4, "text-anchor": "end" });
    label.textContent = valueFormatter(t);
    plot.appendChild(label);
  }
  // X axis (years) — thin out ticks if many years
  const xTickEvery = allYears.length > 8 ? 2 : 1;
  allYears.forEach((yr, i) => {
    if (i % xTickEvery !== 0 && i !== allYears.length - 1) return;
    const x = xScale(yr);
    const label = svgEl("text", { class: "axis-label", x, y: margin.top + plotH + 18, "text-anchor": "middle" });
    label.textContent = String(yr);
    plot.appendChild(label);
  });
  plot.appendChild(svgEl("line", { class: "axis-line", x1: margin.left, x2: margin.left + plotW, y1: margin.top + plotH, y2: margin.top + plotH }));

  // Lines + end markers + end labels
  for (const s of series) {
    const pts = s.points.filter((p) => p.value !== null && !Number.isNaN(p.value)).sort((a, b) => a.year - b.year);
    if (pts.length === 0) continue;
    const d = pts.map((p, i) => `${i === 0 ? "M" : "L"} ${xScale(p.year)} ${yScale(p.value)}`).join(" ");
    plot.appendChild(svgEl("path", { d, fill: "none", stroke: s.color, "stroke-width": 2, "stroke-linejoin": "round", "stroke-linecap": "round" }));

    const last = pts[pts.length - 1];
    const cx = xScale(last.year), cy = yScale(last.value);
    plot.appendChild(svgEl("circle", { cx, cy, r: 4, fill: s.color, stroke: "var(--surface-1)", "stroke-width": 2 }));
    const endLabel = svgEl("text", { class: "axis-label", x: cx + 6, y: cy + 4, fill: s.color, "font-weight": 600 });
    endLabel.textContent = s.iso3 || s.name;
    plot.appendChild(endLabel);

    // Invisible hover targets on each point
    pts.forEach((p) => {
      const hit = svgEl("circle", { cx: xScale(p.year), cy: yScale(p.value), r: 12, fill: "transparent" });
      hit.style.cursor = "pointer";
      hit.addEventListener("pointermove", (evt) => {
        showTooltip(evt.pageX, evt.pageY, `${p.year}`, [{ color: s.color, label: s.name, value: valueFormatter(p.value) }]);
      });
      hit.addEventListener("pointerleave", hideTooltip);
      plot.appendChild(hit);
    });
  }

  renderLegend(container, series);
}

function renderLegend(container, series) {
  if (series.length < 2) return;
  const legend = el("div", { class: "chart-legend" });
  for (const s of series) {
    legend.appendChild(el("span", { class: "legend-item" }, [
      el("span", { class: "legend-swatch", style: `background:${s.color}` }),
      s.name,
    ]));
  }
  container.appendChild(legend);
}

// ---------------------------------------------------------------------
// Horizontal bar chart (CSRI composite)
// ---------------------------------------------------------------------

function renderBarChart(containerId, { bars, valueFormatter = (v) => fmtNum(v), domain = null }) {
  const container = document.getElementById(containerId);
  const rowH = 56;
  const margin = { top: 12, right: 60, bottom: 12, left: 100 };
  const width = 640;
  const height = margin.top + margin.bottom + bars.length * rowH;
  const { svg } = makeChartSVG(container, { width, height, margin });
  const plotW = width - margin.left - margin.right;

  const values = bars.map((b) => b.value).filter((v) => v !== null && !Number.isNaN(v));
  const dom = domain || [0, Math.max(100, ...values)];
  const xScale = scaleLinear(dom, [0, plotW]);

  bars.forEach((b, i) => {
    const y = margin.top + i * rowH;
    const barH = 24;
    const barY = y + (rowH - barH) / 2;

    const label = svgEl("text", { class: "axis-label", x: margin.left - 10, y: barY + barH / 2 + 4, "text-anchor": "end", "font-weight": 600 });
    label.textContent = b.name;
    svg.appendChild(label);

    svg.appendChild(svgEl("line", {
      class: "gridline", x1: margin.left, x2: margin.left + plotW, y1: barY + barH / 2, y2: barY + barH / 2,
    }));

    if (b.value === null || Number.isNaN(b.value)) {
      const naLabel = svgEl("text", { class: "axis-label", x: margin.left + 8, y: barY + barH / 2 + 4 });
      naLabel.textContent = "No data";
      svg.appendChild(naLabel);
      return;
    }

    const barW = Math.max(2, xScale(b.value) - xScale(dom[0]));
    const barX = margin.left + xScale(dom[0]);
    const rect = svgEl("rect", {
      x: barX, y: barY, width: barW, height: barH, rx: 4, fill: b.color,
    });
    rect.style.cursor = "pointer";
    rect.addEventListener("pointermove", (evt) => {
      showTooltip(evt.pageX, evt.pageY, b.name, [{ color: b.color, label: "CSRI", value: valueFormatter(b.value) }]);
    });
    rect.addEventListener("pointerleave", hideTooltip);
    svg.appendChild(rect);

    const valueLabel = svgEl("text", {
      class: "axis-label", x: barX + barW + 8, y: barY + barH / 2 + 4, "font-weight": 600,
    });
    valueLabel.setAttribute("fill", "var(--text-primary)");
    valueLabel.textContent = valueFormatter(b.value);
    svg.appendChild(valueLabel);
  });
}

// ---------------------------------------------------------------------
// Table toggles (accessibility: every chart has a table view)
// ---------------------------------------------------------------------

function buildDataTable(columns, rows) {
  const table = el("table", { class: "data-table" });
  const thead = el("thead", {}, el("tr", {}, columns.map((c) => el("th", { class: c.num ? "num" : "" }, c.label))));
  const tbody = el("tbody", {}, rows.map((r) => el("tr", {}, columns.map((c) => el("td", { class: c.num ? "num" : "" }, c.render(r))))));
  table.appendChild(thead);
  table.appendChild(tbody);
  return table;
}

function wireTableToggle(key) {
  const btn = document.querySelector(`[data-toggle-table="${key}"]`);
  if (!btn) return;
  btn.addEventListener("click", () => {
    const tableEl = document.getElementById(`${key}-table`);
    const chartEl = document.getElementById(`${key}-chart`);
    const showing = !tableEl.hidden;
    tableEl.hidden = showing;
    if (chartEl) chartEl.hidden = !showing;
    btn.setAttribute("aria-expanded", String(!showing));
    btn.textContent = showing ? "View as table" : "View as chart";
  });
}

// ---------------------------------------------------------------------
// Section renderers
// ---------------------------------------------------------------------

function renderKPIRow(snapshot) {
  const row = document.getElementById("kpi-row");
  row.innerHTML = "";
  if (!snapshot) return;
  for (const iso3 of COUNTRY_ORDER) {
    const info = COUNTRIES[iso3];
    const score = snapshot.csri_composite_0_100[iso3];
    const used = snapshot.components_used_per_country[iso3] || [];
    const total = Object.keys(snapshot.weights).length;
    const tile = el("div", { class: "kpi-tile", style: `--tile-accent:${info.color}` }, [
      el("div", { class: "kpi-label" }, [el("span", { class: "kpi-dot" }), info.name]),
      el("div", { class: "kpi-value" }, score === null || Number.isNaN(score) ? "—" : fmtNum(score)),
      el("div", { class: "kpi-sub" }, `Based on ${used.length}/${total} components (see below for exclusions)`),
    ]);
    row.appendChild(tile);
  }
}

function renderCSRIChart(snapshot) {
  if (!snapshot) return;
  const bars = COUNTRY_ORDER
    .map((iso3) => ({ name: COUNTRIES[iso3].name, value: snapshot.csri_composite_0_100[iso3], color: COUNTRIES[iso3].color }))
    .sort((a, b) => (a.value ?? -Infinity) - (b.value ?? -Infinity));
  renderBarChart("csri-chart", { bars, domain: [0, 100] });

  const tableContainer = document.getElementById("csri-table");
  tableContainer.innerHTML = "";
  tableContainer.appendChild(buildDataTable(
    [
      { label: "Country", render: (r) => r.name },
      { label: "CSRI (0-100)", num: true, render: (r) => fmtNum(r.value) },
      { label: "Components used", num: true, render: (r) => `${(snapshot.components_used_per_country[Object.keys(COUNTRIES).find((k) => COUNTRIES[k].name === r.name)] || []).length}/${Object.keys(snapshot.weights).length}` },
    ],
    bars,
  ));
}

function panelSeries(panel, indicatorKey, valueScale = 1) {
  return COUNTRY_ORDER.map((iso3) => ({
    iso3,
    name: COUNTRIES[iso3].name,
    color: COUNTRIES[iso3].color,
    points: panel.filter((r) => r.country_iso3 === iso3).map((r) => ({ year: r.year, value: r[indicatorKey] === null ? null : r[indicatorKey] * valueScale })),
  }));
}

function renderPanelCharts(panel) {
  if (!panel || panel.length === 0) return;

  const inflationSeries = panelSeries(panel, "inflation_cpi_pct");
  renderLineChart("inflation-chart", { series: inflationSeries, useLogScale: true, valueFormatter: (v) => fmtPct(v, 1) });
  document.getElementById("inflation-table").appendChild(
    buildDataTable(
      [{ label: "Country", render: (r) => r.country_name }, { label: "Year", num: true, render: (r) => r.year }, { label: "Inflation %", num: true, render: (r) => fmtPct(r.inflation_cpi_pct) }],
      panel.filter((r) => r.inflation_cpi_pct !== null).sort((a, b) => a.country_iso3.localeCompare(b.country_iso3) || a.year - b.year),
    ),
  );

  const reservesSeries = panelSeries(panel, "reserves_months_imports");
  renderLineChart("reserves-chart", { series: reservesSeries, valueFormatter: (v) => `${fmtNum(v)} mo` });
  document.getElementById("reserves-table").appendChild(
    buildDataTable(
      [{ label: "Country", render: (r) => r.country_name }, { label: "Year", num: true, render: (r) => r.year }, { label: "Months of imports", num: true, render: (r) => fmtNum(r.reserves_months_imports) }],
      panel.filter((r) => r.reserves_months_imports !== null).sort((a, b) => a.country_iso3.localeCompare(b.country_iso3) || a.year - b.year),
    ),
  );

  const debtSeries = panelSeries(panel, "external_debt_gdp_pct");
  renderLineChart("debt-chart", { series: debtSeries, valueFormatter: (v) => fmtPct(v, 1) });
  document.getElementById("debt-table").appendChild(
    buildDataTable(
      [{ label: "Country", render: (r) => r.country_name }, { label: "Year", num: true, render: (r) => r.year }, { label: "External debt / GDP", num: true, render: (r) => fmtPct(r.external_debt_gdp_pct) }],
      panel.filter((r) => r.external_debt_gdp_pct !== null).sort((a, b) => a.country_iso3.localeCompare(b.country_iso3) || a.year - b.year),
    ),
  );

  ["inflation", "reserves", "debt"].forEach(wireTableToggle);
}

function renderFXSpreadPanel(snapshot) {
  const container = document.getElementById("fx-spread-panel");
  container.innerHTML = "";
  if (!snapshot) return;
  const detail = snapshot.zwe_fx_detail;
  // detail.available === false means the live ZimRate fetch failed this
  // pipeline run (e.g. blocked at the network edge for cloud CI runners -
  // see README "Known simplifications"). We show that honestly instead of
  // crashing on missing fields or silently rendering stale/blank numbers -
  // the same "no data" philosophy as the top-level banner.
  if (!detail || detail.available === false) {
    container.appendChild(el("div", { class: "banner" }, [
      el("strong", {}, "Zimbabwe FX snapshot unavailable this run. "),
      document.createTextNode(
        (detail && detail.reason) ||
          "The live ZimRate fetch failed and was not backfilled with a fabricated or stale value. " +
          "See the methodology section's sanity-check log for details.",
      ),
    ]));
    return;
  }
  container.appendChild(el("div", { class: "fx-stat" }, [
    el("div", { class: "fx-label" }, "Official (ZimRate 'official_api' tag)"),
    el("div", { class: "fx-value" }, fmtNum(detail.official_rate_usd_zwg, 2)),
    el("div", { class: "fx-meta" }, `Source: ${detail.official_source_name} · scraped ${new Date(detail.official_scraped_at).toLocaleString()}`),
  ]));
  container.appendChild(el("div", { class: "fx-stat" }, [
    el("div", { class: "fx-label" }, "Parallel / black market"),
    el("div", { class: "fx-value" }, fmtNum(detail.parallel_rate_usd_zwg, 2)),
    el("div", { class: "fx-meta" }, `Source: ${detail.parallel_source_name} · pairs: ${detail.parallel_pairs_used.join(", ")}`),
  ]));
  container.appendChild(el("div", { class: "fx-stat" }, [
    el("div", { class: "fx-label" }, "Spread"),
    el("div", { class: "fx-spread-highlight" }, fmtPct(detail.fx_spread_pct)),
  ]));
}

function renderEventsTimeline(events) {
  const container = document.getElementById("events-timeline");
  container.innerHTML = "";
  if (!events) return;
  const sorted = [...events].sort((a, b) => a.event_date.localeCompare(b.event_date));
  for (const evt of sorted) {
    const info = COUNTRIES[evt.country_iso3] || { name: evt.country_iso3, color: "var(--text-muted)" };
    const row = el("div", { class: "event-row" }, [
      el("div", { class: "event-date" }, evt.event_date),
      el("div", { class: "event-country", style: `color:${info.color}` }, info.name),
      el("div", { class: "event-desc" }, [
        el("strong", {}, evt.event + (evt.magnitude_pct ? ` (${evt.magnitude_pct}%)` : "")),
        document.createTextNode(" — " + (evt.description || "")),
        document.createTextNode(" "),
        el("a", { href: evt.source_url, target: "_blank", rel: "noopener" }, "source"),
      ]),
    ]);
    container.appendChild(row);
  }
}

function renderPolicyTable(decisions) {
  const container = document.getElementById("policy-table");
  container.innerHTML = "";
  if (!decisions) return;
  const sorted = [...decisions].sort((a, b) => a.country_iso3.localeCompare(b.country_iso3) || a.decision_date.localeCompare(b.decision_date));
  container.appendChild(buildDataTable(
    [
      { label: "Country", render: (r) => (COUNTRIES[r.country_iso3] || {}).name || r.country_iso3 },
      { label: "Date", render: (r) => r.decision_date },
      { label: "Rate", num: true, render: (r) => fmtPct(r.policy_rate_pct) },
      { label: "Decision", render: (r) => r.decision },
    ],
    sorted,
  ));
}

function renderIMFStatusPanel(statuses) {
  const container = document.getElementById("imf-status-panel");
  container.innerHTML = "";
  if (!statuses) return;
  for (const iso3 of COUNTRY_ORDER) {
    const row = statuses.find((s) => s.country_iso3 === iso3);
    const info = COUNTRIES[iso3];
    if (!row) continue;
    container.appendChild(el("div", { class: "imf-status-card", style: `border-left:4px solid ${info.color}` }, [
      el("div", { class: "imf-country" }, info.name),
      el("div", { class: "imf-status-text" }, `${row.program_type} — ${row.status}`),
      el("div", { class: "imf-status-text" }, row.description),
      el("div", { class: "imf-source" }, [
        `As of ${row.as_of_date} · `,
        el("a", { href: row.source_url, target: "_blank", rel: "noopener" }, "source"),
      ]),
    ]));
  }
}

function renderMethodology(snapshot, meta) {
  const container = document.getElementById("methodology-body");
  container.innerHTML = "";
  if (!snapshot || !meta) return;

  container.appendChild(el("h3", {}, "Composite index weights"));
  container.appendChild(buildDataTable(
    [{ label: "Component", render: (r) => r[0] }, { label: "Weight", num: true, render: (r) => fmtPct(r[1] * 100) }],
    Object.entries(snapshot.weights),
  ));

  container.appendChild(el("h3", {}, "Excluded components (never silently zeroed)"));
  const exclusionRows = [];
  for (const [iso3, reasons] of Object.entries(snapshot.components_excluded_reasons)) {
    for (const [component, reason] of Object.entries(reasons)) {
      exclusionRows.push({ country: (COUNTRIES[iso3] || {}).name || iso3, component, reason });
    }
  }
  if (exclusionRows.length) {
    container.appendChild(buildDataTable(
      [
        { label: "Country", render: (r) => r.country },
        { label: "Component", render: (r) => r.component },
        { label: "Reason excluded", render: (r) => r.reason },
      ],
      exclusionRows,
    ));
  } else {
    container.appendChild(el("p", {}, "All components were available for all countries in this run."));
  }

  if (meta.sanity_check_warnings && meta.sanity_check_warnings.length) {
    container.appendChild(el("h3", {}, "Sanity check log from this run"));
    container.appendChild(el("ul", {}, meta.sanity_check_warnings.map((w) => el("li", {}, w))));
  }

  container.appendChild(el("h3", {}, "Sources"));
  const sourceList = el("ul", {});
  for (const [k, v] of Object.entries(meta.sources || {})) {
    sourceList.appendChild(el("li", {}, `${k}: ${v}`));
  }
  container.appendChild(sourceList);
}

// ---------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------

async function main() {
  const { data, missing } = await loadAllData();
  renderDataStateBanner(missing);
  renderHeaderMeta(data.meta);
  renderKPIRow(data.latest_snapshot);
  renderCSRIChart(data.latest_snapshot);
  renderPanelCharts(data.panel);
  renderFXSpreadPanel(data.latest_snapshot);
  renderEventsTimeline(data.devaluation_events);
  renderPolicyTable(data.policy_rate_decisions);
  renderIMFStatusPanel(data.imf_program_status);
  renderMethodology(data.latest_snapshot, data.meta);
  wireTableToggle("csri");
}

main();
